Application\Sonata\MediaBundle\Entity\Media:
    product_image-{1..200}:
        __construct: [<uploadedFile()>]

    product_image-soft-pearl-earring:
        __construct: [<uploadedFile('img/product-earring.png')>]

    product_image-soft-pearl-bangle:
        __construct: [<uploadedFile('img/product-bangle.png')>]

    product_image-soft-pearl-ring:
        __construct: [<uploadedFile('img/product-ring.png')>]

    product_image-soft-pearl-pendant:
        __construct: [<uploadedFile('img/product-pendant.png')>]