<?php

namespace Application\Sonata\MediaBundle\Entity;

use Sonata\MediaBundle\Entity\BaseMedia as BaseMedia;
use JMS\Serializer\Annotation\ExclusionPolicy;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 * @ExclusionPolicy("none")
 */
class Media extends BaseMedia
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    public function __construct(UploadedFile $uploadedFile = null)
    {
        if ($uploadedFile) {
            $this->setName($uploadedFile->getFilename());
            $this->setEnabled(true);
            $this->setHeight(480);
            $this->setWidth(640);
            $this->setSize($uploadedFile->getClientSize());
            $this->setProviderName('sonata.media.provider.image');
            $this->setContext('default');
            $this->setBinaryContent(new File($uploadedFile->getRealPath()));
        }
    }
}
