<?php

namespace AppBundle\Repository;

/**
 * BaseFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseFileRepository extends \Doctrine\ORM\EntityRepository
{
}
