<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category,
    AppBundle\Entity\Collection;

/**
 * CollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCollectionOverviewWithProducts(Collection $collection)
    {
        return [
            'ring' => $collection->getFirstProductInCollectionByCategory(Category::CATEGORY_RING),
            'earring' => $collection->getFirstProductInCollectionByCategory(Category::CATEGORY_EARRING),
            'bangle' => $collection->getFirstProductInCollectionByCategory(Category::CATEGORY_BANGLE),
            'pendant' => $collection->getFirstProductInCollectionByCategory(Category::CATEGORY_PENDANT)
        ];
    }
}
