<?php

namespace AppBundle\Repository;

use Liplex\MultipleFileUploadBundle\Repository\MultipleFileUploadRepository;

/**
 * BespokeCarouselRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndexPageCarouselRepository extends MultipleFileUploadRepository
{
}
