<?php

namespace AppBundle\Repository;

use Liplex\MultipleFileUploadBundle\Repository\MultipleFileUploadRepository;
use Doctrine\ORM\EntityRepository;

/**
 * BaseFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends MultipleFileUploadRepository
{
    /**
     * Store one entity.
     *
     * @param mixed $entity
     */
    public function store($entity)
    {
        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush($entity);
    }
}
