<?php

namespace AppBundle\Repository;

/**
 * SliderPictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderPictureRepository extends \Doctrine\ORM\EntityRepository
{
}
