admin:
    resource:   '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix:     /admin

_sonata_admin:
    resource:   .
    type:       sonata_admin
    prefix:     /admin

sonata_user_admin_security:
    resource:   '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix:     /admin

sonata_user_admin_resetting:
    resource:   '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix:     /admin/resetting

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

default:
    resource:   '@AppBundle/Controller/DefaultController.php'
    type:       annotation
    options:
      expose: true

order:
    resource:   '@AppBundle/Controller/OrderController.php'
    type:       annotation

api:
    type:       rest
    prefix:     /api/v1
    resource:   '@AppBundle/Resources/config/routes.yml'
    options:
        expose: true

api_doc:
    resource:   '@NelmioApiDocBundle/Resources/config/routing.yml'
    prefix:     /api/v1/doc

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user_security:
    resource:   '@FOSUserBundle/Resources/config/routing/security.xml'
    prefix:     /api/v1