api:
    type:           rest
    resource:       ApiBundle\Controller\ApiController
    name_prefix:    api_

api_product:
    type:           rest
    resource:       ApiBundle\Controller\ProductApiController
    name_prefix:    api_product_