api:
    type:           rest
    resource:       AppBundle\Controller\ApiController
    name_prefix:    api_

api_product:
    type:           rest
    resource:       AppBundle\Controller\ProductApiController
    name_prefix:    api_product_