services:
    app.admin.listener.serialization-listener:
        class: AppBundle\EventListener\SerializationListener
        tags:
            - { name: jms_serializer.event_subscriber, event: serializer.post_serialize, method: onPostSerialize }
        public: true

    admin_success_handler:
        public: true
        class: AppBundle\Service\AuthenticationHandler
        arguments: [ '@service_container' ]