services:
    app.admin.listener.serialization-listener:
        class: AppBundle\Listener\Serialization\SerializationListener
        tags:
            - { name: jms_serializer.event_subscriber, event: serializer.post_serialize, method: onPostSerialize }
        public: true