services:
    admin.post:
        class: AppBundle\Admin\RingAdmin
        arguments: [~, AppBundle\Entity\Ring, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Product }
        public: true